/**
 * 車両マスターデータ
 * 日本国内で人気の車種データ
 */

import type { Vehicle, MakerInfo, Maker } from "@aska/types";

// =====================================
// メーカー情報
// =====================================

export const MAKERS: MakerInfo[] = [
  // 国産メーカー
  { id: "toyota", name: "トヨタ", nameEn: "Toyota" },
  { id: "lexus", name: "レクサス", nameEn: "Lexus" },
  { id: "honda", name: "ホンダ", nameEn: "Honda" },
  { id: "nissan", name: "日産", nameEn: "Nissan" },
  { id: "mazda", name: "マツダ", nameEn: "Mazda" },
  { id: "subaru", name: "スバル", nameEn: "Subaru" },
  { id: "suzuki", name: "スズキ", nameEn: "Suzuki" },
  { id: "daihatsu", name: "ダイハツ", nameEn: "Daihatsu" },
  { id: "mitsubishi", name: "三菱", nameEn: "Mitsubishi" },
  // ドイツ車
  { id: "bmw", name: "BMW", nameEn: "BMW" },
  { id: "mercedes", name: "メルセデス・ベンツ", nameEn: "Mercedes-Benz" },
  { id: "audi", name: "アウディ", nameEn: "Audi" },
  { id: "volkswagen", name: "フォルクスワーゲン", nameEn: "Volkswagen" },
  { id: "porsche", name: "ポルシェ", nameEn: "Porsche" },
  { id: "mini", name: "MINI", nameEn: "MINI" },
  // その他欧州車
  { id: "volvo", name: "ボルボ", nameEn: "Volvo" },
  { id: "peugeot", name: "プジョー", nameEn: "Peugeot" },
  { id: "renault", name: "ルノー", nameEn: "Renault" },
  { id: "jeep", name: "ジープ", nameEn: "Jeep" },
];

// =====================================
// 車両データ
// =====================================

export const VEHICLES: Vehicle[] = [
  // =====================================
  // トヨタ（日本最大シェア）
  // =====================================
  {
    id: "toyota-prius",
    maker: "toyota",
    makerName: "トヨタ",
    model: "prius",
    modelName: "プリウス",
    category: "standard",
    weight: 1360,
    displacement: 1797,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-aqua",
    maker: "toyota",
    makerName: "トヨタ",
    model: "aqua",
    modelName: "アクア",
    category: "standard",
    weight: 1080,
    displacement: 1490,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-harrier",
    maker: "toyota",
    makerName: "トヨタ",
    model: "harrier",
    modelName: "ハリアー",
    category: "standard",
    weight: 1620,
    displacement: 1986,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-corolla",
    maker: "toyota",
    makerName: "トヨタ",
    model: "corolla",
    modelName: "カローラ",
    category: "standard",
    weight: 1250,
    displacement: 1797,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-voxy",
    maker: "toyota",
    makerName: "トヨタ",
    model: "voxy",
    modelName: "ヴォクシー",
    category: "standard",
    weight: 1640,
    displacement: 1986,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-alphard",
    maker: "toyota",
    makerName: "トヨタ",
    model: "alphard",
    modelName: "アルファード",
    category: "large",
    weight: 2050,
    displacement: 2493,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-yaris",
    maker: "toyota",
    makerName: "トヨタ",
    model: "yaris",
    modelName: "ヤリス",
    category: "standard",
    weight: 1050,
    displacement: 1490,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-yariscross",
    maker: "toyota",
    makerName: "トヨタ",
    model: "yariscross",
    modelName: "ヤリスクロス",
    category: "standard",
    weight: 1180,
    displacement: 1490,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-sienta",
    maker: "toyota",
    makerName: "トヨタ",
    model: "sienta",
    modelName: "シエンタ",
    category: "standard",
    weight: 1300,
    displacement: 1496,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-noah",
    maker: "toyota",
    makerName: "トヨタ",
    model: "noah",
    modelName: "ノア",
    category: "standard",
    weight: 1620,
    displacement: 1986,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-vellfire",
    maker: "toyota",
    makerName: "トヨタ",
    model: "vellfire",
    modelName: "ヴェルファイア",
    category: "large",
    weight: 2070,
    displacement: 2493,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-rav4",
    maker: "toyota",
    makerName: "トヨタ",
    model: "rav4",
    modelName: "RAV4",
    category: "standard",
    weight: 1570,
    displacement: 1986,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-crown",
    maker: "toyota",
    makerName: "トヨタ",
    model: "crown",
    modelName: "クラウン",
    category: "standard",
    weight: 1770,
    displacement: 2487,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-camry",
    maker: "toyota",
    makerName: "トヨタ",
    model: "camry",
    modelName: "カムリ",
    category: "standard",
    weight: 1570,
    displacement: 2487,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-landcruiser",
    maker: "toyota",
    makerName: "トヨタ",
    model: "landcruiser",
    modelName: "ランドクルーザー",
    category: "large",
    weight: 2490,
    displacement: 3444,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-hiace",
    maker: "toyota",
    makerName: "トヨタ",
    model: "hiace",
    modelName: "ハイエース",
    category: "large",
    weight: 1940,
    displacement: 2693,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-roomy",
    maker: "toyota",
    makerName: "トヨタ",
    model: "roomy",
    modelName: "ルーミー",
    category: "standard",
    weight: 1080,
    displacement: 996,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-corollacross",
    maker: "toyota",
    makerName: "トヨタ",
    model: "corollacross",
    modelName: "カローラクロス",
    category: "standard",
    weight: 1410,
    displacement: 1797,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "toyota-86",
    maker: "toyota",
    makerName: "トヨタ",
    model: "gr86",
    modelName: "GR86",
    category: "standard",
    weight: 1270,
    displacement: 2387,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-supra",
    maker: "toyota",
    makerName: "トヨタ",
    model: "supra",
    modelName: "スープラ",
    category: "standard",
    weight: 1520,
    displacement: 2998,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "toyota-bz4x",
    maker: "toyota",
    makerName: "トヨタ",
    model: "bz4x",
    modelName: "bZ4X",
    category: "standard",
    weight: 1920,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // ホンダ
  // =====================================
  {
    id: "honda-nbox",
    maker: "honda",
    makerName: "ホンダ",
    model: "nbox",
    modelName: "N-BOX",
    category: "kei",
    weight: 890,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "honda-fit",
    maker: "honda",
    makerName: "ホンダ",
    model: "fit",
    modelName: "フィット",
    category: "standard",
    weight: 1080,
    displacement: 1496,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "honda-freed",
    maker: "honda",
    makerName: "ホンダ",
    model: "freed",
    modelName: "フリード",
    category: "standard",
    weight: 1410,
    displacement: 1496,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "honda-vezel",
    maker: "honda",
    makerName: "ホンダ",
    model: "vezel",
    modelName: "ヴェゼル",
    category: "standard",
    weight: 1350,
    displacement: 1496,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "honda-nwgn",
    maker: "honda",
    makerName: "ホンダ",
    model: "nwgn",
    modelName: "N-WGN",
    category: "kei",
    weight: 850,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "honda-none",
    maker: "honda",
    makerName: "ホンダ",
    model: "none",
    modelName: "N-ONE",
    category: "kei",
    weight: 840,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "honda-nvan",
    maker: "honda",
    makerName: "ホンダ",
    model: "nvan",
    modelName: "N-VAN",
    category: "kei",
    weight: 930,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "honda-stepwgn",
    maker: "honda",
    makerName: "ホンダ",
    model: "stepwgn",
    modelName: "ステップワゴン",
    category: "standard",
    weight: 1710,
    displacement: 1496,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "honda-civic",
    maker: "honda",
    makerName: "ホンダ",
    model: "civic",
    modelName: "シビック",
    category: "standard",
    weight: 1370,
    displacement: 1496,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "honda-accord",
    maker: "honda",
    makerName: "ホンダ",
    model: "accord",
    modelName: "アコード",
    category: "standard",
    weight: 1560,
    displacement: 1993,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "honda-zrv",
    maker: "honda",
    makerName: "ホンダ",
    model: "zrv",
    modelName: "ZR-V",
    category: "standard",
    weight: 1530,
    displacement: 1496,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "honda-odyssey",
    maker: "honda",
    makerName: "ホンダ",
    model: "odyssey",
    modelName: "オデッセイ",
    category: "large",
    weight: 1890,
    displacement: 2356,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },

  // =====================================
  // 日産
  // =====================================
  {
    id: "nissan-note",
    maker: "nissan",
    makerName: "日産",
    model: "note",
    modelName: "ノート",
    category: "standard",
    weight: 1220,
    displacement: 1198,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "nissan-serena",
    maker: "nissan",
    makerName: "日産",
    model: "serena",
    modelName: "セレナ",
    category: "standard",
    weight: 1740,
    displacement: 1997,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "nissan-xtrail",
    maker: "nissan",
    makerName: "日産",
    model: "xtrail",
    modelName: "エクストレイル",
    category: "standard",
    weight: 1700,
    displacement: 1497,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "nissan-kicks",
    maker: "nissan",
    makerName: "日産",
    model: "kicks",
    modelName: "キックス",
    category: "standard",
    weight: 1350,
    displacement: 1198,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "nissan-leaf",
    maker: "nissan",
    makerName: "日産",
    model: "leaf",
    modelName: "リーフ",
    category: "standard",
    weight: 1520,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "nissan-ariya",
    maker: "nissan",
    makerName: "日産",
    model: "ariya",
    modelName: "アリア",
    category: "standard",
    weight: 1920,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "nissan-sakura",
    maker: "nissan",
    makerName: "日産",
    model: "sakura",
    modelName: "サクラ",
    category: "kei",
    weight: 1070,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "nissan-dayz",
    maker: "nissan",
    makerName: "日産",
    model: "dayz",
    modelName: "デイズ",
    category: "kei",
    weight: 840,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "nissan-roox",
    maker: "nissan",
    makerName: "日産",
    model: "roox",
    modelName: "ルークス",
    category: "kei",
    weight: 950,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "nissan-skyline",
    maker: "nissan",
    makerName: "日産",
    model: "skyline",
    modelName: "スカイライン",
    category: "standard",
    weight: 1760,
    displacement: 2997,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "nissan-fairlady",
    maker: "nissan",
    makerName: "日産",
    model: "fairlady",
    modelName: "フェアレディZ",
    category: "standard",
    weight: 1570,
    displacement: 2997,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "nissan-elgrand",
    maker: "nissan",
    makerName: "日産",
    model: "elgrand",
    modelName: "エルグランド",
    category: "large",
    weight: 2010,
    displacement: 2488,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },

  // =====================================
  // スズキ
  // =====================================
  {
    id: "suzuki-spacia",
    maker: "suzuki",
    makerName: "スズキ",
    model: "spacia",
    modelName: "スペーシア",
    category: "kei",
    weight: 850,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-hustler",
    maker: "suzuki",
    makerName: "スズキ",
    model: "hustler",
    modelName: "ハスラー",
    category: "kei",
    weight: 820,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-swift",
    maker: "suzuki",
    makerName: "スズキ",
    model: "swift",
    modelName: "スイフト",
    category: "standard",
    weight: 970,
    displacement: 1242,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-alto",
    maker: "suzuki",
    makerName: "スズキ",
    model: "alto",
    modelName: "アルト",
    category: "kei",
    weight: 680,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-wagonr",
    maker: "suzuki",
    makerName: "スズキ",
    model: "wagonr",
    modelName: "ワゴンR",
    category: "kei",
    weight: 790,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-jimny",
    maker: "suzuki",
    makerName: "スズキ",
    model: "jimny",
    modelName: "ジムニー",
    category: "kei",
    weight: 1040,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-jimnysierra",
    maker: "suzuki",
    makerName: "スズキ",
    model: "jimnysierra",
    modelName: "ジムニーシエラ",
    category: "standard",
    weight: 1090,
    displacement: 1460,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-escudo",
    maker: "suzuki",
    makerName: "スズキ",
    model: "escudo",
    modelName: "エスクード",
    category: "standard",
    weight: 1230,
    displacement: 1586,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-solio",
    maker: "suzuki",
    makerName: "スズキ",
    model: "solio",
    modelName: "ソリオ",
    category: "standard",
    weight: 1010,
    displacement: 1242,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-xbee",
    maker: "suzuki",
    makerName: "スズキ",
    model: "xbee",
    modelName: "クロスビー",
    category: "standard",
    weight: 960,
    displacement: 996,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-lapin",
    maker: "suzuki",
    makerName: "スズキ",
    model: "lapin",
    modelName: "ラパン",
    category: "kei",
    weight: 680,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "suzuki-every",
    maker: "suzuki",
    makerName: "スズキ",
    model: "every",
    modelName: "エブリイ",
    category: "kei",
    weight: 950,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },

  // =====================================
  // ダイハツ
  // =====================================
  {
    id: "daihatsu-tanto",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "tanto",
    modelName: "タント",
    category: "kei",
    weight: 880,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-move",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "move",
    modelName: "ムーヴ",
    category: "kei",
    weight: 820,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-rocky",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "rocky",
    modelName: "ロッキー",
    category: "standard",
    weight: 1050,
    displacement: 1196,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-mira",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "mira",
    modelName: "ミラ イース",
    category: "kei",
    weight: 650,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-taft",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "taft",
    modelName: "タフト",
    category: "kei",
    weight: 830,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-canbus",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "canbus",
    modelName: "ムーヴ キャンバス",
    category: "kei",
    weight: 870,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-atrai",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "atrai",
    modelName: "アトレー",
    category: "kei",
    weight: 970,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-hijet",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "hijet",
    modelName: "ハイゼット",
    category: "kei",
    weight: 900,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-cast",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "cast",
    modelName: "キャスト",
    category: "kei",
    weight: 840,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "daihatsu-thor",
    maker: "daihatsu",
    makerName: "ダイハツ",
    model: "thor",
    modelName: "トール",
    category: "standard",
    weight: 1080,
    displacement: 996,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },

  // =====================================
  // マツダ
  // =====================================
  {
    id: "mazda-cx5",
    maker: "mazda",
    makerName: "マツダ",
    model: "cx5",
    modelName: "CX-5",
    category: "standard",
    weight: 1540,
    displacement: 1997,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mazda-mazda3",
    maker: "mazda",
    makerName: "マツダ",
    model: "mazda3",
    modelName: "MAZDA3",
    category: "standard",
    weight: 1350,
    displacement: 1997,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mazda-cx30",
    maker: "mazda",
    makerName: "マツダ",
    model: "cx30",
    modelName: "CX-30",
    category: "standard",
    weight: 1380,
    displacement: 1997,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mazda-cx8",
    maker: "mazda",
    makerName: "マツダ",
    model: "cx8",
    modelName: "CX-8",
    category: "large",
    weight: 1780,
    displacement: 2488,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mazda-cx60",
    maker: "mazda",
    makerName: "マツダ",
    model: "cx60",
    modelName: "CX-60",
    category: "standard",
    weight: 1860,
    displacement: 2488,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mazda-mazda2",
    maker: "mazda",
    makerName: "マツダ",
    model: "mazda2",
    modelName: "MAZDA2",
    category: "standard",
    weight: 1020,
    displacement: 1496,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mazda-roadster",
    maker: "mazda",
    makerName: "マツダ",
    model: "roadster",
    modelName: "ロードスター",
    category: "standard",
    weight: 1000,
    displacement: 1496,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mazda-mx30",
    maker: "mazda",
    makerName: "マツダ",
    model: "mx30",
    modelName: "MX-30",
    category: "standard",
    weight: 1460,
    displacement: 1997,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },

  // =====================================
  // スバル
  // =====================================
  {
    id: "subaru-forester",
    maker: "subaru",
    makerName: "スバル",
    model: "forester",
    modelName: "フォレスター",
    category: "standard",
    weight: 1570,
    displacement: 1795,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "subaru-impreza",
    maker: "subaru",
    makerName: "スバル",
    model: "impreza",
    modelName: "インプレッサ",
    category: "standard",
    weight: 1340,
    displacement: 1995,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "subaru-xv",
    maker: "subaru",
    makerName: "スバル",
    model: "xv",
    modelName: "クロストレック",
    category: "standard",
    weight: 1540,
    displacement: 1995,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "subaru-outback",
    maker: "subaru",
    makerName: "スバル",
    model: "outback",
    modelName: "アウトバック",
    category: "standard",
    weight: 1680,
    displacement: 1795,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "subaru-levorg",
    maker: "subaru",
    makerName: "スバル",
    model: "levorg",
    modelName: "レヴォーグ",
    category: "standard",
    weight: 1550,
    displacement: 1795,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "subaru-wrx",
    maker: "subaru",
    makerName: "スバル",
    model: "wrx",
    modelName: "WRX S4",
    category: "standard",
    weight: 1580,
    displacement: 2387,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "subaru-brz",
    maker: "subaru",
    makerName: "スバル",
    model: "brz",
    modelName: "BRZ",
    category: "standard",
    weight: 1260,
    displacement: 2387,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "subaru-solterra",
    maker: "subaru",
    makerName: "スバル",
    model: "solterra",
    modelName: "ソルテラ",
    category: "standard",
    weight: 1930,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // 三菱
  // =====================================
  {
    id: "mitsubishi-outlander",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "outlander",
    modelName: "アウトランダー",
    category: "standard",
    weight: 2010,
    displacement: 2359,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "mitsubishi-delica",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "delica",
    modelName: "デリカD:5",
    category: "large",
    weight: 1960,
    displacement: 2267,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mitsubishi-ek",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "ek",
    modelName: "eKワゴン",
    category: "kei",
    weight: 840,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mitsubishi-ekspace",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "ekspace",
    modelName: "eKスペース",
    category: "kei",
    weight: 950,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mitsubishi-ekx",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "ekx",
    modelName: "eKクロス",
    category: "kei",
    weight: 860,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mitsubishi-ekxev",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "ekxev",
    modelName: "eKクロスEV",
    category: "kei",
    weight: 1080,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "mitsubishi-eclipse",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "eclipse",
    modelName: "エクリプスクロス",
    category: "standard",
    weight: 1550,
    displacement: 1499,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mitsubishi-rvr",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "rvr",
    modelName: "RVR",
    category: "standard",
    weight: 1420,
    displacement: 1798,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mitsubishi-minicab",
    maker: "mitsubishi",
    makerName: "三菱",
    model: "minicab",
    modelName: "ミニキャブ",
    category: "kei",
    weight: 900,
    displacement: 658,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },

  // =====================================
  // レクサス
  // =====================================
  {
    id: "lexus-rx",
    maker: "lexus",
    makerName: "レクサス",
    model: "rx",
    modelName: "RX",
    category: "large",
    weight: 2100,
    displacement: 2487,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "lexus-nx",
    maker: "lexus",
    makerName: "レクサス",
    model: "nx",
    modelName: "NX",
    category: "standard",
    weight: 1790,
    displacement: 2487,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "lexus-ux",
    maker: "lexus",
    makerName: "レクサス",
    model: "ux",
    modelName: "UX",
    category: "standard",
    weight: 1550,
    displacement: 1986,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "lexus-is",
    maker: "lexus",
    makerName: "レクサス",
    model: "is",
    modelName: "IS",
    category: "standard",
    weight: 1680,
    displacement: 2493,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "lexus-es",
    maker: "lexus",
    makerName: "レクサス",
    model: "es",
    modelName: "ES",
    category: "standard",
    weight: 1730,
    displacement: 2487,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "lexus-ls",
    maker: "lexus",
    makerName: "レクサス",
    model: "ls",
    modelName: "LS",
    category: "large",
    weight: 2270,
    displacement: 3444,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "lexus-lx",
    maker: "lexus",
    makerName: "レクサス",
    model: "lx",
    modelName: "LX",
    category: "large",
    weight: 2680,
    displacement: 3444,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "lexus-lc",
    maker: "lexus",
    makerName: "レクサス",
    model: "lc",
    modelName: "LC",
    category: "standard",
    weight: 1980,
    displacement: 4968,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "lexus-rc",
    maker: "lexus",
    makerName: "レクサス",
    model: "rc",
    modelName: "RC",
    category: "standard",
    weight: 1720,
    displacement: 2493,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "lexus-rz",
    maker: "lexus",
    makerName: "レクサス",
    model: "rz",
    modelName: "RZ",
    category: "standard",
    weight: 2090,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // BMW
  // =====================================
  {
    id: "bmw-3series",
    maker: "bmw",
    makerName: "BMW",
    model: "3series",
    modelName: "3シリーズ",
    category: "standard",
    weight: 1570,
    displacement: 1998,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "bmw-5series",
    maker: "bmw",
    makerName: "BMW",
    model: "5series",
    modelName: "5シリーズ",
    category: "standard",
    weight: 1780,
    displacement: 1998,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "bmw-x1",
    maker: "bmw",
    makerName: "BMW",
    model: "x1",
    modelName: "X1",
    category: "standard",
    weight: 1620,
    displacement: 1499,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "bmw-x3",
    maker: "bmw",
    makerName: "BMW",
    model: "x3",
    modelName: "X3",
    category: "standard",
    weight: 1860,
    displacement: 1998,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "bmw-x5",
    maker: "bmw",
    makerName: "BMW",
    model: "x5",
    modelName: "X5",
    category: "large",
    weight: 2290,
    displacement: 2998,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "bmw-1series",
    maker: "bmw",
    makerName: "BMW",
    model: "1series",
    modelName: "1シリーズ",
    category: "standard",
    weight: 1450,
    displacement: 1499,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "bmw-2series",
    maker: "bmw",
    makerName: "BMW",
    model: "2series",
    modelName: "2シリーズ",
    category: "standard",
    weight: 1560,
    displacement: 1998,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "bmw-ix",
    maker: "bmw",
    makerName: "BMW",
    model: "ix",
    modelName: "iX",
    category: "large",
    weight: 2440,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "bmw-i4",
    maker: "bmw",
    makerName: "BMW",
    model: "i4",
    modelName: "i4",
    category: "standard",
    weight: 2050,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // メルセデス・ベンツ
  // =====================================
  {
    id: "mercedes-aclass",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "aclass",
    modelName: "Aクラス",
    category: "standard",
    weight: 1450,
    displacement: 1331,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-cclass",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "cclass",
    modelName: "Cクラス",
    category: "standard",
    weight: 1680,
    displacement: 1496,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-eclass",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "eclass",
    modelName: "Eクラス",
    category: "standard",
    weight: 1870,
    displacement: 1991,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-sclass",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "sclass",
    modelName: "Sクラス",
    category: "large",
    weight: 2190,
    displacement: 2996,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-gla",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "gla",
    modelName: "GLA",
    category: "standard",
    weight: 1570,
    displacement: 1331,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-glb",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "glb",
    modelName: "GLB",
    category: "standard",
    weight: 1700,
    displacement: 1331,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-glc",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "glc",
    modelName: "GLC",
    category: "standard",
    weight: 1900,
    displacement: 1991,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-gle",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "gle",
    modelName: "GLE",
    category: "large",
    weight: 2290,
    displacement: 2996,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mercedes-eqa",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "eqa",
    modelName: "EQA",
    category: "standard",
    weight: 2040,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "mercedes-eqb",
    maker: "mercedes",
    makerName: "メルセデス・ベンツ",
    model: "eqb",
    modelName: "EQB",
    category: "standard",
    weight: 2150,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // アウディ
  // =====================================
  {
    id: "audi-a3",
    maker: "audi",
    makerName: "アウディ",
    model: "a3",
    modelName: "A3",
    category: "standard",
    weight: 1420,
    displacement: 1498,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "audi-a4",
    maker: "audi",
    makerName: "アウディ",
    model: "a4",
    modelName: "A4",
    category: "standard",
    weight: 1600,
    displacement: 1984,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "audi-a6",
    maker: "audi",
    makerName: "アウディ",
    model: "a6",
    modelName: "A6",
    category: "standard",
    weight: 1800,
    displacement: 1984,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "audi-q3",
    maker: "audi",
    makerName: "アウディ",
    model: "q3",
    modelName: "Q3",
    category: "standard",
    weight: 1610,
    displacement: 1498,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "audi-q5",
    maker: "audi",
    makerName: "アウディ",
    model: "q5",
    modelName: "Q5",
    category: "standard",
    weight: 1870,
    displacement: 1984,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "audi-q7",
    maker: "audi",
    makerName: "アウディ",
    model: "q7",
    modelName: "Q7",
    category: "large",
    weight: 2220,
    displacement: 2994,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "audi-etron",
    maker: "audi",
    makerName: "アウディ",
    model: "etron",
    modelName: "e-tron",
    category: "large",
    weight: 2560,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "audi-q4etron",
    maker: "audi",
    makerName: "アウディ",
    model: "q4etron",
    modelName: "Q4 e-tron",
    category: "standard",
    weight: 2100,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // フォルクスワーゲン
  // =====================================
  {
    id: "volkswagen-golf",
    maker: "volkswagen",
    makerName: "フォルクスワーゲン",
    model: "golf",
    modelName: "ゴルフ",
    category: "standard",
    weight: 1370,
    displacement: 1497,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volkswagen-polo",
    maker: "volkswagen",
    makerName: "フォルクスワーゲン",
    model: "polo",
    modelName: "ポロ",
    category: "standard",
    weight: 1200,
    displacement: 999,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volkswagen-tiguan",
    maker: "volkswagen",
    makerName: "フォルクスワーゲン",
    model: "tiguan",
    modelName: "ティグアン",
    category: "standard",
    weight: 1680,
    displacement: 1497,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volkswagen-passat",
    maker: "volkswagen",
    makerName: "フォルクスワーゲン",
    model: "passat",
    modelName: "パサート",
    category: "standard",
    weight: 1590,
    displacement: 1497,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volkswagen-tcross",
    maker: "volkswagen",
    makerName: "フォルクスワーゲン",
    model: "tcross",
    modelName: "T-Cross",
    category: "standard",
    weight: 1280,
    displacement: 999,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volkswagen-troc",
    maker: "volkswagen",
    makerName: "フォルクスワーゲン",
    model: "troc",
    modelName: "T-Roc",
    category: "standard",
    weight: 1440,
    displacement: 1497,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volkswagen-id4",
    maker: "volkswagen",
    makerName: "フォルクスワーゲン",
    model: "id4",
    modelName: "ID.4",
    category: "standard",
    weight: 2140,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // MINI
  // =====================================
  {
    id: "mini-cooper",
    maker: "mini",
    makerName: "MINI",
    model: "cooper",
    modelName: "クーパー",
    category: "standard",
    weight: 1240,
    displacement: 1499,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mini-clubman",
    maker: "mini",
    makerName: "MINI",
    model: "clubman",
    modelName: "クラブマン",
    category: "standard",
    weight: 1420,
    displacement: 1499,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mini-countryman",
    maker: "mini",
    makerName: "MINI",
    model: "countryman",
    modelName: "クロスオーバー",
    category: "standard",
    weight: 1540,
    displacement: 1499,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "mini-electric",
    maker: "mini",
    makerName: "MINI",
    model: "electric",
    modelName: "エレクトリック",
    category: "standard",
    weight: 1440,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // ボルボ
  // =====================================
  {
    id: "volvo-xc40",
    maker: "volvo",
    makerName: "ボルボ",
    model: "xc40",
    modelName: "XC40",
    category: "standard",
    weight: 1680,
    displacement: 1968,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volvo-xc60",
    maker: "volvo",
    makerName: "ボルボ",
    model: "xc60",
    modelName: "XC60",
    category: "standard",
    weight: 1890,
    displacement: 1968,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volvo-xc90",
    maker: "volvo",
    makerName: "ボルボ",
    model: "xc90",
    modelName: "XC90",
    category: "large",
    weight: 2140,
    displacement: 1968,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volvo-v60",
    maker: "volvo",
    makerName: "ボルボ",
    model: "v60",
    modelName: "V60",
    category: "standard",
    weight: 1750,
    displacement: 1968,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volvo-s60",
    maker: "volvo",
    makerName: "ボルボ",
    model: "s60",
    modelName: "S60",
    category: "standard",
    weight: 1720,
    displacement: 1968,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "volvo-c40",
    maker: "volvo",
    makerName: "ボルボ",
    model: "c40",
    modelName: "C40 Recharge",
    category: "standard",
    weight: 2130,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
  {
    id: "volvo-ex30",
    maker: "volvo",
    makerName: "ボルボ",
    model: "ex30",
    modelName: "EX30",
    category: "standard",
    weight: 1790,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // ポルシェ
  // =====================================
  {
    id: "porsche-cayenne",
    maker: "porsche",
    makerName: "ポルシェ",
    model: "cayenne",
    modelName: "カイエン",
    category: "large",
    weight: 2100,
    displacement: 2995,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "porsche-macan",
    maker: "porsche",
    makerName: "ポルシェ",
    model: "macan",
    modelName: "マカン",
    category: "standard",
    weight: 1890,
    displacement: 1984,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "porsche-911",
    maker: "porsche",
    makerName: "ポルシェ",
    model: "911",
    modelName: "911",
    category: "standard",
    weight: 1550,
    displacement: 2981,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "porsche-taycan",
    maker: "porsche",
    makerName: "ポルシェ",
    model: "taycan",
    modelName: "タイカン",
    category: "large",
    weight: 2305,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // ジープ
  // =====================================
  {
    id: "jeep-wrangler",
    maker: "jeep",
    makerName: "ジープ",
    model: "wrangler",
    modelName: "ラングラー",
    category: "large",
    weight: 2020,
    displacement: 1995,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "jeep-grandcherokee",
    maker: "jeep",
    makerName: "ジープ",
    model: "grandcherokee",
    modelName: "グランドチェロキー",
    category: "large",
    weight: 2290,
    displacement: 2987,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "jeep-compass",
    maker: "jeep",
    makerName: "ジープ",
    model: "compass",
    modelName: "コンパス",
    category: "standard",
    weight: 1560,
    displacement: 1331,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "jeep-renegade",
    maker: "jeep",
    makerName: "ジープ",
    model: "renegade",
    modelName: "レネゲード",
    category: "standard",
    weight: 1440,
    displacement: 1331,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },

  // =====================================
  // プジョー
  // =====================================
  {
    id: "peugeot-208",
    maker: "peugeot",
    makerName: "プジョー",
    model: "208",
    modelName: "208",
    category: "standard",
    weight: 1170,
    displacement: 1199,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "peugeot-308",
    maker: "peugeot",
    makerName: "プジョー",
    model: "308",
    modelName: "308",
    category: "standard",
    weight: 1380,
    displacement: 1199,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "peugeot-2008",
    maker: "peugeot",
    makerName: "プジョー",
    model: "2008",
    modelName: "2008",
    category: "standard",
    weight: 1270,
    displacement: 1199,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "peugeot-3008",
    maker: "peugeot",
    makerName: "プジョー",
    model: "3008",
    modelName: "3008",
    category: "standard",
    weight: 1510,
    displacement: 1598,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "peugeot-5008",
    maker: "peugeot",
    makerName: "プジョー",
    model: "5008",
    modelName: "5008",
    category: "standard",
    weight: 1610,
    displacement: 1598,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "peugeot-e208",
    maker: "peugeot",
    makerName: "プジョー",
    model: "e208",
    modelName: "e-208",
    category: "standard",
    weight: 1530,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },

  // =====================================
  // ルノー
  // =====================================
  {
    id: "renault-kangoo",
    maker: "renault",
    makerName: "ルノー",
    model: "kangoo",
    modelName: "カングー",
    category: "standard",
    weight: 1490,
    displacement: 1333,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "renault-captur",
    maker: "renault",
    makerName: "ルノー",
    model: "captur",
    modelName: "キャプチャー",
    category: "standard",
    weight: 1350,
    displacement: 1333,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "renault-lutecia",
    maker: "renault",
    makerName: "ルノー",
    model: "lutecia",
    modelName: "ルーテシア",
    category: "standard",
    weight: 1210,
    displacement: 1333,
    isEco: false,
    isHybrid: false,
    isElectric: false,
  },
  {
    id: "renault-arkana",
    maker: "renault",
    makerName: "ルノー",
    model: "arkana",
    modelName: "アルカナ",
    category: "standard",
    weight: 1450,
    displacement: 1333,
    isEco: true,
    isHybrid: true,
    isElectric: false,
  },
  {
    id: "renault-megane",
    maker: "renault",
    makerName: "ルノー",
    model: "megane",
    modelName: "メガーヌ E-TECH",
    category: "standard",
    weight: 1710,
    displacement: 0,
    isEco: true,
    isHybrid: false,
    isElectric: true,
  },
];

// =====================================
// ヘルパー関数
// =====================================

/**
 * メーカーIDからメーカー情報を取得
 */
export function getMaker(makerId: Maker): MakerInfo | undefined {
  return MAKERS.find((m) => m.id === makerId);
}

/**
 * 車両IDから車両情報を取得
 */
export function getVehicle(vehicleId: string): Vehicle | undefined {
  return VEHICLES.find((v) => v.id === vehicleId);
}

/**
 * メーカー別の車両一覧を取得
 */
export function getVehiclesByMaker(makerId: Maker): Vehicle[] {
  return VEHICLES.filter((v) => v.maker === makerId);
}

/**
 * 全車両のIDリストを取得（静的生成用）
 */
export function getAllVehicleIds(): string[] {
  return VEHICLES.map((v) => v.id);
}

/**
 * メーカーとモデルからパスパラメータを生成
 */
export function getVehicleParams(): { maker: string; model: string }[] {
  return VEHICLES.map((v) => ({
    maker: v.maker,
    model: v.model,
  }));
}
